export { default as Header} from './Header/Header'
export { default as About} from './About/About'
export { default as Team} from './Team/Team'
export { default as Lessons} from './Lessons/Lessons'
export { default as Rentals} from './Rentals/Rentals'
export { default as Gallery} from './Gallery/Gallery'
export { default as ContactUs} from './ContactUs/ContactUs'
export { default as Footer} from './Footer/Footer'